server:
  port: 8095

spring:
  profiles:
    active: docker # Cambia a 'docker' para Docker

# La config de seguridad se define en application-local.yml y application-docker.yml
# La config de seguridad se define en application-local.yml y application-docker.yml
